# Generated by Django 5.2.5 on 2025-08-31 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('area_metros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corregimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='LineaTecnologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='NivelFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedConocimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.dia')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.horario')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.jornada'),
        ),
        migrations.AddField(
            model_name='horario',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.modalidad'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.ambiente')),
                ('corregimientos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.corregimientos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='corregimientos',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.municipio'),
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('version', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_programa', models.CharField(choices=[('COMPLEMENTARIA', 'Complementaria'), ('TITULADA', 'Titulada')], default='COMPLEMENTARIA', max_length=20)),
                ('duracion', models.IntegerField()),
                ('duracion_etapa_lectiva', models.IntegerField()),
                ('duracion_etapa_productiva', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('linea_tecnologica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='ofertas.lineatecnologica')),
                ('nivel_formacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='ofertas.nivelformacion')),
                ('red_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='ofertas.redconocimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modalidad_oferta', models.CharField(choices=[('CAMPESENA', 'Campesena'), ('REGULAR', 'Regular')], default='REGULAR', max_length=20)),
                ('tipo_oferta', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('entorno_geografico', models.CharField(choices=[('RURAL', 'Rural'), ('URBANO', 'Urbano')], default='URBANO', max_length=10)),
                ('cupo', models.IntegerField()),
                ('empresa_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('subsector', models.CharField(blank=True, max_length=255, null=True)),
                ('convenio', models.CharField(blank=True, max_length=255, null=True)),
                ('ficha', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_de_solicitud', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('fecha_de_inscripcion', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.estado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ofertas.horario')),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ofertas.lugar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('programa_especial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ofertas.programaespecial')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.programaformacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vereda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('corregimientos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ofertas.corregimientos')),
            ],
        ),
    ]
