# Generated by Django 5.2.5 on 2025-08-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('subsector_economico', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='empresa_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ofertas.empresasolicitante'),
        ),
    ]
