# Generated by Django 5.2.5 on 2025-09-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_empresasolicitante_alter_oferta_empresa_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programaformacion',
            name='nivel_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='ofertas.nivelformacion'),
        ),
    ]
