# Generated by Django 5.2.5 on 2025-09-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0003_alter_programaformacion_nivel_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redconocimientos',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
