# Generated by Django 5.2.5 on 2025-09-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_alter_redconocimientos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineatecnologica',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programaformacion',
            name='nivel_formacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='ofertas.nivelformacion'),
        ),
    ]
