# Generated by Django 5.2.5 on 2025-09-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_alter_lineatecnologica_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='subsector',
        ),
    ]
