# Generated by Django 5.2.5 on 2025-09-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_remove_oferta_convenio_remove_oferta_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='archivo',
            field=models.FileField(blank=True, default='', upload_to='ofertas/'),
        ),
    ]
