# Generated by Django 5.2.5 on 2025-09-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_oferta_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_de_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
