# Generated by Django 5.2.5 on 2025-09-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0008_alter_oferta_fecha_de_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
