# Generated by Django 5.2.4 on 2025-09-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0009_alter_oferta_fecha_terminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
