# Generated by Django 5.2.4 on 2025-09-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0010_oferta_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='color',
        ),
        migrations.AddField(
            model_name='oferta',
            name='archivo_cedula_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cedulas/'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
