# Generated by Django 5.2.5 on 2025-09-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0011_remove_estado_color_oferta_archivo_cedula_pdf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modalidad',
            new_name='ModalidadPrograma',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='oferta',
            name='modalidad_programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ofertas.modalidadprograma'),
        ),
    ]
