# Generated by Django 5.2.5 on 2025-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0012_rename_modalidad_modalidadprograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='jornada',
        ),
    ]
