# Generated by Django 5.2.5 on 2025-09-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0012_rename_modalidad_modalidadprograma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='archivo_cedula_pdf',
        ),
        migrations.AddField(
            model_name='oferta',
            name='caracterizacion_generada',
            field=models.FileField(blank=True, null=True, upload_to='ficha_caracterizacion/'),
        ),
    ]
