# Generated by Django 5.2.5 on 2025-09-11 02:17

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_remove_horario_jornada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='horario_dias',
            field=models.ManyToManyField(blank=True, to='ofertas.horariodia'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='corregimientos',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipio', chained_model_field='municipio', on_delete=django.db.models.deletion.PROTECT, to='ofertas.corregimientos'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='municipio',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='departamento', chained_model_field='departamento', on_delete=django.db.models.deletion.PROTECT, to='ofertas.municipio'),
        ),
    ]
