# Generated by Django 5.2.5 on 2025-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0014_oferta_horario_dias_alter_lugar_corregimientos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='ambiente',
            field=models.CharField(max_length=255),
        ),
    ]
