# Generated by Django 5.2.5 on 2025-09-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0015_alter_lugar_ambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
