# Generated by Django 5.2.5 on 2025-09-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0016_alter_oferta_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='horario',
        ),
        migrations.AddField(
            model_name='oferta',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='ofertas', to='ofertas.horario'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='horario_dias',
            field=models.ManyToManyField(to='ofertas.horariodia'),
        ),
    ]
