# Generated by Django 5.2.4 on 2025-09-12 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0017_remove_oferta_horario_oferta_horarios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ofertas/')),
                ('tipo', models.CharField(choices=[('word', 'Word'), ('excel', 'Excel'), ('pdf', 'PDF'), ('otro', 'Otro')], default='otro', max_length=10)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='ofertas.oferta')),
            ],
        ),
    ]
