# Generated by Django 5.2.5 on 2025-09-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0017_remove_oferta_horario_oferta_horarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='archivo',
            field=models.FileField(blank=True, default='', upload_to='cartas_solicitud/'),
        ),
    ]
