# Generated by Django 5.2.6 on 2025-09-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_remove_horario_jornada'),
        ('ofertas', '0018_alter_oferta_archivo'),
    ]

    operations = [
    ]
