# Generated by Django 5.2.5 on 2025-09-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.area'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='es_verificado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_identificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_identificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipoidentificacion'),
        ),
    ]
