# Generated by Django 5.2.5 on 2025-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía')], default='CC', max_length=2, verbose_name='Tipo de Identificación')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('tipo_poblacion_aspirante', models.CharField(max_length=100, verbose_name='Tipo Población Aspirante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
