# Generated by Django 5.2.5 on 2025-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='celular',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='tipo_poblacion_aspirante',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Víctima del conflicto', 'Víctima del conflicto'), ('Madre cabeza de familia', 'Madre cabeza de familia'), ('Afrocolombiano', 'Afrocolombiano'), ('Indígena', 'Indígena'), ('Discapacitado', 'Discapacitado'), ('Desplazado por la violencia', 'Desplazado por la violencia')], default='Ninguna', max_length=100, verbose_name='Tipo Población Aspirante'),
        ),
    ]
